### ISSUE TITLE
Problème des années bisextiles

### ISSUE THREAD

**Issue by popy-dev** [Lamecarlate/republican-calendar#1]
[Le site/système bug les 29 févriers](http://informatique.lamecarlate.net/web/experiences/republican-calendar/?month=02&day=29)

Le premier mars, il n'y a plus d'erreur visible, mais on se retrouve au  11 Ventose, alors que ca devrait être le 12.

Et pour pinailler : les années bisextiles du calendrier républicain ne sont pas sensées tomber les mêmes années que celles du calendrier grégorien.

**Comment by Lamecarlate** [comment]
Bonjour,

merci de votre retour. 

Je sais hélas que mon petit calendrier ne prend pas en compte les années bissextiles grégoriennes - d'ailleurs les années sextiles républicaines non plus (dans mon article de présentation https://informatique.lamecarlate.net/articles/le-calendrier-republicain je l'avais indiqué). C'était un projet sur un week-end, et je n'y ai plus retouché depuis (flemme, tout ça).

Cependant, qu'il y ait des erreurs affichées, c'est nul.

Je vais essayer de prendre du temps pour corriger, mais pour l'instant je ne garantis rien… Si vous avez une idée entre temps, n'hésitez pas à faire une pull request :)

**Comment by popy-dev** [comment]
Ok, j'essayerais de faire une PR :)

**Comment by Lamecarlate** [comment]
PR acceptée, je ferme ici.

**Comment by popy-dev** [comment]
Cool, bonne continuation :)
